version: '3.8'
services:
  web:
    build: app
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    environment:
      - DB_HOST=db
    depends_on:
      - db
      - redis
    env_file: .env
  db:
    image: postgres:alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    env_file: .env
  celery:
    restart: always
    build: app
    command: celery -A etutor worker -l info
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
      - redis
      - web

volumes:
  db:
    driver: local
  redis:
    driver: local