# Generated by Django 4.0.5 on 2022-08-31 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('sender_psid', models.CharField(max_length=50)),
                ('request_data', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('place', models.CharField(choices=[('online', 'Online'), ('client', "At client's place"), ('tutor', "At tutor's place")], default='online', max_length=30)),
                ('money_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_repetitive', models.BooleanField(default=True)),
                ('is_sending_reminder', models.BooleanField(default=True)),
                ('is_facebook_notification_send', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('avatar_img_path', models.CharField(blank=True, max_length=300)),
                ('facebook_psid', models.CharField(max_length=50)),
                ('send_reminder_hours_before', models.IntegerField(default=1)),
                ('send_reminders_to_yourself', models.BooleanField(default=False)),
                ('send_reminders_to_students', models.BooleanField(default=False)),
                ('message_template_to_yourself', models.CharField(blank=True, max_length=500)),
                ('message_template_to_students', models.CharField(blank=True, max_length=500)),
                ('account_active', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('discord_nick', models.CharField(blank=True, max_length=50)),
                ('facebook_profile', models.CharField(blank=True, max_length=150)),
                ('facebook_psid', models.CharField(blank=True, max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor'),
        ),
    ]
