# Generated by Django 4.0.5 on 2022-09-14 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('place', models.CharField(choices=[('Online', 'Online'), ("Client's", "Client's"), ("Tutor's", "Tutor's")], default='Online', max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=250)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_repetitive', models.BooleanField(default=True)),
                ('is_notification_send', models.BooleanField(default=False)),
                ('send_facebook_message', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('facebook_psid', models.CharField(default='5458874970818405', max_length=50)),
                ('message_template_to_tutor', models.CharField(blank=True, default='\n    Hej,\n    {subject} z {sfname} {slname}.\n    Lekcje odbywają się: {start}.\n    \n    Miejsce: {place}\n    Adres: {address}\n    \n    Dodatkowy opis: {description}\n    ', max_length=500)),
                ('message_template_to_student', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('discord_nick', models.CharField(blank=True, max_length=50, unique=True)),
                ('facebook_profile', models.CharField(blank=True, max_length=150, unique=True)),
                ('facebook_psid', models.CharField(blank=True, max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Payment due')], default='due', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor'),
        ),
    ]
