# Generated by Django 4.0.5 on 2022-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='facebook_notification_send',
            new_name='is_facebook_notification_send',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='repetitive',
            new_name='is_repetitive',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='send_reminder',
            new_name='is_sending_reminder',
        ),
        migrations.AddField(
            model_name='lesson',
            name='money_per_hour',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.CharField(choices=[('online', 'Online'), ('at clients', "At client's place"), ('at tutors', "At tutor's place")], default='online', max_length=30),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='discord_nick',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
