# Generated by Django 4.0.5 on 2022-06-29 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_color_alter_task_list_id_delete_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 40, 2, 519075)),
        ),
    ]
