# Generated by Django 4.0.5 on 2022-08-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_facebook_notification_send_lesson_is_facebook_notification_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='facebook_psid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
