# Generated by Django 4.0.5 on 2022-06-30 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_list_id_task_user_id_remove_task_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_starred', 'is_done', '-start_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 19, 22, 30, 421979)),
        ),
    ]
