# Generated by Django 4.0.5 on 2022-07-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_student_id_lesson_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 22, 46, 32, 983859)),
        ),
    ]
